import Layout from "@/components/custom/Layout";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import Providers from "./providers";

import "@/modules/pintura/pintura.css";
import "./globals.css";

const _DMSans = DM_Sans({ subsets: ["latin"], variable: "--font-dm-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${_DMSans.variable} font-dm-sans antialiased dark`}>
        <Providers>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
